apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: eaera-acr-secret
    namespace: '{{ .Values.namespace }}'
spec:
    suspend: false
    secretTemplates:
        - name: ENC[AES256_GCM,data:Pcw/PFg0emgA,iv:3cy5qsevk0oUJGhRt1HEEy8ebh7AxrWEMDknVKuwD/g=,tag:0L3koE0/bKH79a629nRpeA==,type:str]
          type: ENC[AES256_GCM,data:KkY7X+0co8islmV84sSmqVIA4yHnY0Nyd0SHg8cn,iv:3BfSm69pB0j7pokpiLIuSlmwCm/tSz4cfFA3aU2hzeY=,tag:3YoJg+7eVEtXkHoFRqXi8Q==,type:str]
          stringData:
            .dockerconfigjson: ENC[AES256_GCM,data:FXvqj+w57aOyUUXS7UIbJE+xAaCvWrPRtNBH64vYXuYQUtC0Kmovl6jmfpuki98Jv7kWCIHmdLbOXlVd0aSjKPTgdd7OwoWHwYAlsK0oOBYsaLnkP8ur8dTzHFiBlgJ3kVjXWxUF8nx9aaE+fNEncIIs9RCl9wRQWWubQdu32DdFRAsRlKivghOURcIhSySz6UgwZLUhnBTwJ+g9Vqs2,iv:aV3LEn2zkkambwF9h9t7xyjdTVe6sncdeiGhq8i3srg=,tag:mJ6jMis2/HFs8Hqtb4u+1g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://eaera-keyvault.vault.azure.net
          name: sops-key
          version: c23ad20e79e2430c8ec19bd721840435
          created_at: "2024-01-30T04:44:26Z"
          enc: mhwaULb7jqegjs2dwR8CCfrNqr1opYwoycyTer55AjIEd85YvU0Z5o5xHxLsJgnu7VvwGnKFU2cJChO4yJ6Q1N_BcyzyEmbEcZqET72iJFf-286G1HCNVd4I8YSigtLvt9kVwuCV5Eyex1VhTXxheejX_61YjkNmWr3enSeow93sDgL3Cx4tpyVpWWOmrmKUSTvGJIsavVBo8fJw34x8MHG4D2bQYFvnRuktQu-rSr-XiXOCxc2f9ui5EzOQsTN0hU_RuS29eHV46Y7T75YYVw9ibygPoJc_eefsWRgqLar1d_OxNFbdYz7jAbi0PxX1R1TdyZGPsYTC_jk5VHboRg
    hc_vault: []
    age: []
    lastmodified: "2024-01-30T04:44:28Z"
    mac: ENC[AES256_GCM,data:7WLOgDq9RsXkrshTGKTjLXgqTYJ9dZPsMDAVVVT/YyHaZ0zxcFy6odHtgBkoWqkwO1CzXlBAC5V4cK8YHLvkE+RkqNFzdz0zxCvNvsBBfM0ZGNL9Gja2Q85YEDZ69XPu9wTcU1X3YNVo2+U+Jw/H69bBvf9PTPz7lc/leGtyXYU=,iv:bxO+emBo8aSuB3Qmx+YeHq25oYdyIS7CY/aoe0yF0Oc=,tag:KY0N8kCYVMwlDNIHA8lbFw==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.7.3
