apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: libretranslate
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
spec:
  ingressClassName: "nginx"
  rules:
  - host: {{ $.Values.ingress.host | default (printf "libretranslate.%s" $.Values.domain) }}
    http:
      paths:
      - backend:
          service:
            name: libretranslate
            port:
              number: 5000
        path: /
        pathType: Prefix
  tls: # < placing a host in the TLS config will determine what ends up in the cert's subjectAltNames
  - hosts:
    - {{ $.Values.ingress.host | default (printf "libretranslate.%s" $.Values.domain) }}
    secretName: {{ .Values.namespace }}-libretranslate-cert
