apiVersion: v1
kind: Service
metadata:
  name: libretranslate
  namespace: {{ .Values.namespace }}
  labels:
    app: libretranslate
spec:
  selector:
    app: libretranslate
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
