namespace: libretranslate
domain: uk2.eaera.com
ingress:
  host: libretranslate.uk2.eaera.com
storage:
  size: 32Gi
  storageClassName: premium2-disk-sc
  persistentVolume:
    enabled: true
    volumeHandle: /subscriptions/ca345c4a-2897-4c58-abce-a7598b1630cb/resourceGroups/rg-eaera-sea/providers/Microsoft.Compute/disks/LibreTranslateData
  dbNodeAffinity:
  - key: topology.disk.csi.azure.com/zone
    operator: In
    value: southeastasia-2
tolerations:
- key: agentpool
  operator: Equal
  value: app
  effect: NoSchedule